server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:12345678@tcp(127.0.0.1:3306)/kratos?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
register:
  consul:
    address: 127.0.0.1:8500
    scheme: http
